module: "src.agents.api_agents.OpenAIChatCompletion"
parameters:
  name: "gpt-4"
  api_args:
    model: "gpt-4"
    key: Bearer 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
    base: https://api.openai.com/v1/chat/completions
    timeout: 120
